language: generic

sudo: required

after_success: |
  wget https://raw.githubusercontent.com/thelastparadox/mediacentreinstaller/master/mediacentreinstaller.sh
  bash mediacentreinstaller.sh --headless
